version: '3'

services:
  front:
    build:
      context: .
    ports:
    - 5000

  back:
    image: gtrias/goby-api
    links:
    - db
    ports:
    - ${PORT-8080}:3000
  db:
    image: mongo:latest
